server:
  port: 8082
spring:
  application:
    name: Confluent Producer
  cloud:
    stream:
      bindings:
        output:
          destination: producerTopic
      kafka:
        binder:
          brokers: <CONFLUENT_HOST>.confluent.cloud:9092
          configuration:
            ssl.endpoint.identification.algorithm: https
            sasl.mechanism: PLAIN
            request.timeout.ms: 20000
            retry.backoff.ms: 500
            sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="<API_KEY>" password="<API_SECRET>";
            security.protocol: SASL_SSL
          replication-factor: 3